name: 'insightops_demo'
version: '1.0.0'
config-version: 2
profile: 'insightops_demo'
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  insightops_demo:
    staging:
      +schema: DEMO_STG
      +materialized: view
    intermediate:
      +schema: DEMO_INT
      +materialized: view
    facts:
      +schema: DEMO_FCT
      +materialized: table
    marts:
      +schema: DEMO_MART
      +materialized: table
