insightops_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "INLDKNQ-LATENTVIEW_COMMON_ACCOUNT"
      user: "mohamed.arshath@latentview.com"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "BET_ROLE"
      warehouse: "BET_WH"
      database: "BET_DB"
      schema: "DEMO_STG"
      threads: 4
      client_session_keep_alive: False
      query_tag: insightops_demo_dbt
